# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s= "Hi there Sam!"
k=s.split()
print(s)

Hi there Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [5]:
planet ="Earth"
diameter= 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
lst[3][1][2][0]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
array=np.arange(20,36,1)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
arr = np.concatenate((a, b))
print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [23]:
import pandas as pd
df = pd.DataFrame({'S.NO':['1','2','3'],
                   'Name':['Karthi','sura','praveen'],
                   'Name1':['srinath','Gowtham','praveen']})
df


S.NO     Name    Name1
0    1   Karthi  srinath
1    2     sura  Gowtham
2    3  praveen  praveen

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
import datetime
today = datetime.date.today()
new_year = datetime.date(2023, 1, 1)
new_years =datetime.date(2023,2,10)
print(new_year)
print(new_years)

2023-01-01
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [33]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]